"use client"

import { useEffect, useMemo, useState } from "react"
import { CheckCircle2, Clock3, DatabaseBackup, Download, Plus, RotateCcw, ShieldAlert } from "lucide-react"

const initialEvents: { id: string; type: string; scheduled: string; completed: string; status: string; provider: string }[] = []

export function BackupPage() {
  const [events, setEvents] = useState(initialEvents)
  const [showForm, setShowForm] = useState(false)
  useEffect(() => { fetch('/api/dashboard-state', { cache: 'no-store' }).then((response) => response.ok ? response.json() : null).then((data) => { if (Array.isArray(data?.backups) && data.backups.length) setEvents(data.backups.map((event: any) => ({ id: event.id, type: event.backupType, scheduled: new Date(event.scheduledFor).toLocaleString(), completed: event.completedAt ? new Date(event.completedAt).toLocaleString() : '—', status: event.status === 'completed' ? 'Completed' : 'Missed', provider: event.provider }))) }).catch(() => undefined) }, [])
  const missed = useMemo(() => events.filter((event) => event.status === "Missed"), [events])
  const today = new Date().toDateString()
  const dailyToday = events.some((event) => event.type === 'Daily backup' && event.status === 'Completed' && new Date(event.completed).toDateString() === today)
  const recoveryToday = events.some((event) => event.type === 'Weekly recovery test' && event.status === 'Completed' && new Date(event.completed).toDateString() === today)
  return <div className="flex flex-col gap-5">
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Daily status" value={dailyToday ? "1 / 1" : "0 / 1"} detail={dailyToday ? "Completed today" : "No check recorded today"} tone={dailyToday ? "good" : "neutral"}/><Metric label="Weekly status" value={recoveryToday ? "1 / 1" : "0 / 1"} detail={recoveryToday ? "Recovery test passed" : "No test recorded today"} tone={recoveryToday ? "good" : "neutral"}/><Metric label="Missed events" value={String(missed.length)} detail={missed.length ? "Needs administrator review" : "No missed events"} tone={missed.length ? "bad" : "good"}/><Metric label="Next scheduled" value="—" detail="No schedule recorded" tone="neutral"/></div>
    {missed.length > 0 && <div className="flex items-start gap-3 rounded-xl border border-[#f0dadd] bg-[#fffafb] p-4 text-sm"><ShieldAlert className="mt-0.5 text-[#c44857]" size={18}/><div><p className="font-bold text-[#a93c4b]">Backup attention required</p><p className="mt-1 text-xs text-[#7d6266]">A backup is more than 12 hours late. The n8n notification contract will alert every configured system email and the administrator.</p></div></div>}
    <section className="rounded-xl border border-[#e3e7eb] bg-white p-5"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div><div className="flex items-center gap-2"><DatabaseBackup size={18} className="text-[#176b71]"/><h2 className="text-[16px] font-bold">Backup & recovery log</h2></div><p className="mt-1 text-xs text-[#8b979e]">Daily backups and weekly recovery tests are tracked in WAT.</p></div><div className="flex gap-2"><button onClick={() => setShowForm(true)} className="rounded-lg bg-[#176b71] px-3 py-2 text-xs font-bold text-white"><Plus size={14} className="mr-1 inline"/>Record event</button><button className="rounded-lg border border-[#dce3e6] px-3 py-2 text-xs font-bold text-[#64727a]"><Download size={14} className="mr-1 inline"/>Export log</button></div></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[720px] text-left text-xs"><thead><tr className="border-b border-[#edf0f1] text-[10px] uppercase tracking-wider text-[#a0abb1]"><th className="pb-3">Event</th><th className="pb-3">Scheduled</th><th className="pb-3">Completed</th><th className="pb-3">Provider</th><th className="pb-3">Status</th></tr></thead><tbody>{events.map((event) => <tr key={event.id} className="border-b border-[#f0f2f3] last:border-0"><td className="py-4 font-bold">{event.type}</td><td className="py-4 text-[#718087]">{event.scheduled}</td><td className="py-4 text-[#718087]">{event.completed}</td><td className="py-4 text-[#718087]">{event.provider}</td><td className="py-4"><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${event.status === "Completed" ? "bg-[#e8f7f1] text-[#18765c]" : "bg-[#fff0f1] text-[#c44857]"}`}>{event.status}</span></td></tr>)}</tbody></table></div></section>
    <section className="grid gap-4 lg:grid-cols-2"><InfoCard icon={<Clock3 size={17}/>} title="Missed-event rules" copy="Daily: alert after 12 hours from the start of the WAT day. Weekly: alert after 2 days from the end of the WAT week."/><InfoCard icon={<RotateCcw size={17}/>} title="Recovery readiness" copy="Record a completed recovery test weekly and retain the provider, completion time, operator, and notes for audit."/></section>
    {showForm && <RecordEvent onClose={() => setShowForm(false)} onSave={async (event) => { const response = await fetch('/api/dashboard-state', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ type: 'backup', event }) }); if (response.ok) { const result = await response.json(); setEvents((current) => [{ id: result.backup.id, type: result.backup.backupType, scheduled: new Date(result.backup.scheduledFor).toLocaleString(), completed: result.backup.completedAt ? new Date(result.backup.completedAt).toLocaleString() : '—', status: result.backup.status === 'completed' ? 'Completed' : 'Missed', provider: result.backup.provider }, ...current]); setShowForm(false) } }}/>}</div>
}
function Metric({ label, value, detail, tone }: { label: string; value: string; detail: string; tone: string }) { return <div className="rounded-xl border border-[#e3e7eb] bg-white p-4"><p className="text-xs font-semibold text-[#7a878f]">{label}</p><p className={`mt-3 text-2xl font-extrabold ${tone === "bad" ? "text-[#c44857]" : "text-[#26343c]"}`}>{value}</p><p className="mt-1 text-[11px] text-[#9aa4aa]">{detail}</p></div> }
function InfoCard({ icon, title, copy }: { icon: React.ReactNode; title: string; copy: string }) { return <div className="rounded-xl border border-[#e3e7eb] bg-white p-5"><div className="flex items-center gap-2 text-[#176b71]"><span className="flex size-8 items-center justify-center rounded-lg bg-[#e6f4f1]">{icon}</span><h3 className="text-sm font-bold text-[#26343c]">{title}</h3></div><p className="mt-4 text-xs leading-5 text-[#718087]">{copy}</p></div> }
function RecordEvent({ onClose, onSave }: { onClose: () => void; onSave: (event: typeof initialEvents[number]) => void }) { const [type, setType] = useState("Daily backup"); return <div className="fixed inset-0 z-50 flex items-center justify-center bg-[#14222a]/40 p-4"><form onSubmit={(event) => { event.preventDefault(); onSave({ id: String(Date.now()), type, scheduled: "Sep 09, 2026 · 00:00 WAT", completed: "Just now · WAT", status: "Completed", provider: "Manual / n8n" }) }} className="w-full max-w-[420px] rounded-2xl bg-white p-6 shadow-2xl"><h2 className="text-xl font-extrabold">Record backup event</h2><p className="mt-1 text-xs text-[#8b979e]">Use this for an operator-confirmed backup or recovery test.</p><label className="mt-5 block text-xs font-bold">Event type<select value={type} onChange={(event) => setType(event.target.value)} className="mt-2 h-10 w-full rounded-lg border border-[#dce3e6] bg-white px-3 text-sm"><option>Daily backup</option><option>Weekly recovery test</option></select></label><div className="mt-6 flex justify-end gap-2"><button type="button" onClick={onClose} className="rounded-lg border border-[#dce3e6] px-4 py-2 text-sm font-bold text-[#64727a]">Cancel</button><button className="rounded-lg bg-[#176b71] px-4 py-2 text-sm font-bold text-white">Save event</button></div></form></div> }
