"use client"

import { useMemo, useState } from "react"
import Link from "next/link"
import { usePathname } from "next/navigation"
import { Bell, CalendarDays, Camera, Check, ChevronRight, CircleHelp, CloudDownload, Database, Download, FileText, LayoutDashboard, LifeBuoy, LogOut, Menu, MoreHorizontal, Plus, Search, Settings, ShieldCheck, SlidersHorizontal, Users, X } from "lucide-react"

const cameras = [
  { station: "North Field", name: "Camera 01", id: "CAM-NF-001", location: "North perimeter", status: "online", seen: "2 min ago", firmware: "v4.8.2", uptime: "99.8%", incidents: 0, address: "10.42.14.21" },
  { station: "North Field", name: "Camera 02", id: "CAM-NF-002", location: "Pump house", status: "offline", seen: "18 min ago", firmware: "v4.8.2", uptime: "97.1%", incidents: 3, address: "10.42.14.22" },
  { station: "Main Gate", name: "Camera 03", id: "CAM-MG-003", location: "Entry gate", status: "online", seen: "1 min ago", firmware: "v4.7.9", uptime: "99.9%", incidents: 0, address: "10.42.10.18" },
  { station: "Main Gate", name: "Camera 04", id: "CAM-MG-004", location: "Loading bay", status: "offline", seen: "41 min ago", firmware: "v4.7.9", uptime: "96.3%", incidents: 5, address: "10.42.10.19" },
]

const subscriptions = [
  { name: "SentinelOne", category: "Security", owner: "IT Operations", expires: "Sep 08, 2026", days: 5, status: "Expiring Soon", cost: "$8,400", initials: "S1" },
  { name: "Figma Professional", category: "Design", owner: "Product Design", expires: "Sep 12, 2026", days: 9, status: "Expiring Soon", cost: "$2,160", initials: "FG" },
  { name: "GitHub Enterprise", category: "Dev Tools", owner: "Engineering", expires: "Sep 24, 2026", days: 21, status: "Active", cost: "$4,800", initials: "GH" },
  { name: "Microsoft 365", category: "Productivity", owner: "People Ops", expires: "Oct 03, 2026", days: 30, status: "Active", cost: "$18,600", initials: "M3" },
]

const nav = [
  { href: "/", label: "Overview", icon: LayoutDashboard },
  { href: "/subscriptions", label: "Subscriptions", icon: FileText },
  { href: "/calendar", label: "Renewal calendar", icon: CalendarDays },
  { href: "/forecast", label: "Spend forecast", icon: Database },
  { href: "/cameras", label: "Camera status", icon: Camera },
]

export function FarmAlertApp({ page = "overview" }: { page?: string }) {
  const [mobileNav, setMobileNav] = useState(false)
  const [selectedCamera, setSelectedCamera] = useState<(typeof cameras)[number] | null>(null)
  const [query, setQuery] = useState("")
  const path = usePathname()
  const current = page === "overview" ? "Overview" : page[0].toUpperCase() + page.slice(1)
  const filtered = useMemo(() => subscriptions.filter((item) => `${item.name} ${item.category} ${item.owner}`.toLowerCase().includes(query.toLowerCase())), [query])

  return <div className="min-h-screen bg-[#f7f9fa] text-[#24313a]">
    <header className="sticky top-0 z-30 flex h-[68px] items-center justify-between border-b border-[#e3e8eb] bg-white/95 px-5 backdrop-blur md:px-8"><div className="flex items-center gap-3"><button onClick={() => setMobileNav(true)} className="rounded-lg p-2 text-[#6e7b84] md:hidden" aria-label="Open navigation"><Menu /></button><Link href="/" className="flex items-center gap-3"><div className="flex size-9 items-center justify-center rounded-xl bg-[#176b71] text-white"><ShieldCheck size={19}/></div><div><p className="text-[15px] font-bold tracking-tight">farm alert IT</p><p className="text-[10px] font-medium uppercase tracking-[.18em] text-[#99a4ab]">Operations console</p></div></Link></div><div className="flex items-center gap-2"><Link href="/settings" className="rounded-lg p-2 text-[#6d7a83] hover:bg-[#f3f6f7]" aria-label="Settings"><Settings size={18}/></Link><Link href="/login" className="flex items-center gap-2 rounded-lg border border-[#dce3e6] px-3 py-2 text-xs font-semibold text-[#55636d]"><span className="hidden sm:inline">Admin access</span><LogOut size={15}/></Link></div></header>
    <div className="flex"><aside className={`${mobileNav ? "fixed inset-y-0 left-0 z-50 flex" : "hidden"} w-[250px] flex-col border-r border-[#e3e8eb] bg-white p-4 md:sticky md:top-[68px] md:flex md:h-[calc(100vh-68px)]`}><div className="mb-5 flex items-center justify-between px-3"><span className="text-[10px] font-bold uppercase tracking-[.16em] text-[#a0abb1]">Workspace</span><button className="md:hidden" onClick={() => setMobileNav(false)} aria-label="Close navigation"><X size={18}/></button></div><nav className="flex flex-col gap-1">{nav.map((item) => { const Icon = item.icon; return <Link key={item.href} onClick={() => setMobileNav(false)} href={item.href} className={`flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-semibold ${path === item.href ? "bg-[#e8f3f2] text-[#176b71]" : "text-[#65737c] hover:bg-[#f5f7f8]"}`}><Icon size={17}/>{item.label}{item.label === "Camera status" && <span className="ml-auto rounded-full bg-[#fff0f1] px-2 py-0.5 text-[10px] text-[#c44857]">2</span>}</Link>})}</nav><div className="mt-7 border-t border-[#edf0f1] pt-5"><p className="px-3 pb-2 text-[10px] font-bold uppercase tracking-[.16em] text-[#a0abb1]">Manage</p><nav className="flex flex-col gap-1"><Link href="/admin" className="flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-semibold text-[#65737c] hover:bg-[#f5f7f8]"><Users size={17}/>Admin center</Link><Link href="/settings" className="flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-semibold text-[#65737c] hover:bg-[#f5f7f8]"><SlidersHorizontal size={17}/>Settings</Link></nav></div><div className="mt-auto rounded-xl bg-[#f3f7f7] p-3"><div className="flex items-center gap-2 text-xs font-bold text-[#176b71]"><LifeBuoy size={15}/> IT support</div><p className="mt-2 text-[11px] leading-4 text-[#78858c]">Need help managing an account or camera?</p><button className="mt-2 text-[11px] font-bold text-[#176b71]">Open support request <ChevronRight className="inline" size={12}/></button></div></aside>{mobileNav && <button aria-label="Close menu" onClick={() => setMobileNav(false)} className="fixed inset-0 z-40 bg-[#16252c]/25 md:hidden"/>}
      <main className="min-w-0 flex-1 px-5 py-6 md:px-8 md:py-8"><div className="mx-auto max-w-[1320px]"><div className="mb-7 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><div className="mb-2 flex items-center gap-2 text-xs text-[#95a1a8]"><Link href="/">farm alert IT</Link><ChevronRight size={13}/><span>{current}</span></div><h1 className="text-[27px] font-extrabold tracking-[-.03em] text-[#26343c]">{page === "overview" ? "Good morning, Sam" : current}</h1><p className="mt-1 text-sm text-[#7f8b92]">{page === "overview" ? "Here’s what needs your attention today." : page === "cameras" ? "Monitor heartbeat health across every farm station." : "Manage the information your IT team relies on."}</p></div>{page === "overview" && <Link href="/subscriptions" className="flex items-center justify-center gap-2 rounded-lg bg-[#176b71] px-4 py-2.5 text-sm font-semibold text-white shadow-sm"><Plus size={16}/> Add subscription</Link>}</div>{page === "overview" ? <Overview setSelectedCamera={setSelectedCamera} /> : page === "cameras" ? <CameraPage setSelectedCamera={setSelectedCamera} /> : page === "admin" ? <AdminPanel /> : page === "settings" ? <SettingsPanel /> : <SectionPage page={page} query={query} setQuery={setQuery} filtered={filtered}/>}</div></main></div>{selectedCamera && <CameraModal camera={selectedCamera} onClose={() => setSelectedCamera(null)} />}</div>
}

function Overview({ setSelectedCamera }: { setSelectedCamera: (camera: (typeof cameras)[number]) => void }) { return <><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Total subscriptions" value="24" helper="Across 8 departments" icon={<FileText/>}/><Stat label="Expiring in 10 days" value="3" helper="Needs action this week" icon={<Bell/>} accent="amber"/><Stat label="Expired" value="1" helper="Requires immediate attention" icon={<CircleHelp/>} accent="red"/><Stat label="Annual spend" value="$86,420" helper="Projected renewal cost" icon={<Database/>} accent="teal"/></section><CameraStrip setSelectedCamera={setSelectedCamera}/><section className="mt-6 rounded-xl border border-[#e3e7eb] bg-white p-5"><div className="flex items-center justify-between"><div><h2 className="text-[16px] font-bold">Subscription renewals</h2><p className="mt-1 text-xs text-[#8b979e]">The next software renewals that need planning</p></div><Link href="/subscriptions" className="text-xs font-bold text-[#176b71]">View all <ChevronRight className="inline" size={13}/></Link></div><SubscriptionTable compact/></section></> }
function Stat({ label, value, helper, icon, accent = "slate" }: { label: string; value: string; helper: string; icon: React.ReactNode; accent?: string }) { const colors: Record<string,string> = { slate: "bg-[#eef2f3] text-[#677780]", amber: "bg-[#fff5db] text-[#d29226]", red: "bg-[#fff0f1] text-[#cc5562]", teal: "bg-[#e6f4f1] text-[#21807d]" }; return <div className="rounded-xl border border-[#e3e7eb] bg-white p-4 shadow-[0_1px_2px_rgba(20,35,50,.03)]"><div className="flex items-start justify-between"><span className="text-xs font-semibold text-[#7a878f]">{label}</span><span className={`flex size-8 items-center justify-center rounded-lg ${colors[accent]}`}>{icon}</span></div><p className="mt-4 text-[27px] font-extrabold tracking-tight">{value}</p><p className="mt-1 text-[11px] text-[#9aa4aa]">{helper}</p></div> }
function CameraStrip({ setSelectedCamera }: { setSelectedCamera: (camera: (typeof cameras)[number]) => void }) { return <section className="mt-6 rounded-xl border border-[#e3e7eb] bg-white p-5"><div className="flex items-center justify-between"><div><div className="flex items-center gap-2"><Camera size={17} className="text-[#176b71]"/><h2 className="text-[16px] font-bold">CCTV camera status</h2></div><p className="mt-1 text-xs text-[#8b979e]">Live station health from n8n observations</p></div><Link href="/cameras" className="text-xs font-bold text-[#176b71]">Open camera center <ChevronRight className="inline" size={13}/></Link></div><div className="mt-4 grid gap-3 md:grid-cols-4">{cameras.map((camera) => <button key={camera.id} onClick={() => setSelectedCamera(camera)} className={`rounded-xl border p-4 text-left transition hover:-translate-y-0.5 hover:shadow-md ${camera.status === "online" ? "border-[#d9ece7] bg-[#fbfefd]" : "border-[#f0dadd] bg-[#fffafb]"}`}><div className="flex items-start justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.13em] text-[#94a0a8]">{camera.station}</p><p className="mt-1 text-sm font-bold">{camera.name}</p></div><span className={`size-3 rounded-full ${camera.status === "online" ? "bg-[#25a878] shadow-[0_0_0_4px_#dff5eb]" : "bg-[#df5b67] shadow-[0_0_0_4px_#fde6e8]"}`}/></div><p className="mt-3 text-xs text-[#697781]">{camera.location}</p><p className={`mt-3 text-[11px] ${camera.status === "online" ? "text-[#38826f]" : "font-semibold text-[#c45861]"}`}>{camera.status === "online" ? `Seen ${camera.seen}` : `Offline · ${camera.seen}`}</p></button>)}</div></section> }
function SubscriptionTable({ compact = false }: { compact?: boolean }) { return <div className="mt-4 overflow-x-auto"><table className="w-full min-w-[700px] text-left text-xs"><thead><tr className="border-b border-[#edf0f1] text-[10px] uppercase tracking-wider text-[#a0abb1]"><th className="pb-3">Software</th><th className="pb-3">Category</th><th className="pb-3">Owner</th><th className="pb-3">Expiration</th><th className="pb-3">Status</th><th className="pb-3">Annual cost</th><th/></tr></thead><tbody>{subscriptions.slice(0, compact ? 4 : subscriptions.length).map((item) => <tr key={item.name} className="border-b border-[#f0f2f3] last:border-0"><td className="py-4"><div className="flex items-center gap-3"><span className="flex size-8 items-center justify-center rounded-lg bg-[#edf3f4] text-[10px] font-bold text-[#176b71]">{item.initials}</span><span className="font-bold">{item.name}</span></div></td><td className="py-4 text-[#728089]">{item.category}</td><td className="py-4 text-[#728089]">{item.owner}</td><td className="py-4 font-semibold">{item.expires}<span className="ml-2 text-[10px] text-[#9ba5aa]">{item.days}d</span></td><td className="py-4"><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${item.status === "Active" ? "bg-[#e8f7f1] text-[#18765c]" : "bg-[#fff5db] text-[#b57920]"}`}>{item.status}</span></td><td className="py-4 font-semibold">{item.cost}</td><td><MoreHorizontal size={16} className="text-[#a1abb1]"/></td></tr>)}</tbody></table></div> }
function CameraPage({ setSelectedCamera }: { setSelectedCamera: (camera: (typeof cameras)[number]) => void }) { return <><div className="mb-5 grid gap-4 sm:grid-cols-3"><Stat label="Total cameras" value="4" helper="Across 2 stations" icon={<Camera/>}/><Stat label="Online now" value="2" helper="Heartbeat within 10 minutes" icon={<Check/>} accent="teal"/><Stat label="Offline" value="2" helper="Requires investigation" icon={<Bell/>} accent="red"/></div><section className="rounded-xl border border-[#e3e7eb] bg-white p-5"><div className="flex items-center justify-between"><div><h2 className="text-[16px] font-bold">All station cameras</h2><p className="mt-1 text-xs text-[#8b979e]">Click any camera to inspect health, history, and incidents.</p></div><button className="rounded-lg border border-[#dce3e6] px-3 py-2 text-xs font-bold text-[#64727a]"><Download size={14} className="mr-1 inline"/>Export history</button></div><div className="mt-5 grid gap-4 md:grid-cols-2">{cameras.map((camera) => <button onClick={() => setSelectedCamera(camera)} key={camera.id} className="rounded-xl border border-[#e6eaec] p-5 text-left hover:border-[#9bc9c6] hover:shadow-sm"><div className="flex justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.13em] text-[#94a0a8]">{camera.station}</p><h3 className="mt-1 font-bold">{camera.name}</h3></div><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${camera.status === "online" ? "bg-[#e8f7f1] text-[#18765c]" : "bg-[#fff0f1] text-[#c44857]"}`}>{camera.status}</span></div><div className="mt-5 grid grid-cols-2 gap-3 text-xs"><div><p className="text-[#9aa5ab]">Location</p><p className="mt-1 font-semibold">{camera.location}</p></div><div><p className="text-[#9aa5ab]">Last heartbeat</p><p className="mt-1 font-semibold">{camera.seen}</p></div><div><p className="text-[#9aa5ab]">Uptime, 30 days</p><p className="mt-1 font-semibold">{camera.uptime}</p></div><div><p className="text-[#9aa5ab]">Open incidents</p><p className="mt-1 font-semibold">{camera.incidents}</p></div></div></button>)}</div></section></> }
function SectionPage({ page, query, setQuery, filtered }: { page: string; query: string; setQuery: (value: string) => void; filtered: typeof subscriptions }) { const title = page === "subscriptions" ? "Software subscriptions" : page === "calendar" ? "Renewal calendar" : "Spend forecast"; return <section className="rounded-xl border border-[#e3e7eb] bg-white p-5"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-center"><div><h2 className="text-[16px] font-bold">{title}</h2><p className="mt-1 text-xs text-[#8b979e]">{page === "subscriptions" ? "Search, filter, export, and renew every SaaS subscription." : page === "calendar" ? "Upcoming renewal dates and alert windows for the whole team." : "Projected renewal costs grouped by month and department."}</p></div>{page === "subscriptions" && <div className="flex items-center gap-2 rounded-lg border border-[#dfe5e7] px-3 py-2"><Search size={15} className="text-[#a1abb1]"/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search subscriptions" className="w-full text-xs outline-none"/></div>}</div>{page === "subscriptions" ? <><SubscriptionTable/><div className="mt-5 flex items-center justify-between border-t border-[#edf0f1] pt-4 text-xs text-[#8b979e]"><span>{filtered.length} subscriptions shown</span><button className="font-bold text-[#176b71]">Export CSV <CloudDownload className="inline" size={14}/></button></div></> : <div className="mt-6 grid gap-3 md:grid-cols-3">{["September 2026", "October 2026", "November 2026"].map((month, index) => <div key={month} className="rounded-xl border border-[#e7ebed] p-5"><p className="text-xs font-bold text-[#176b71]">{month}</p><p className="mt-4 text-2xl font-extrabold">{index === 0 ? "$15,360" : index === 1 ? "$18,600" : "$7,420"}</p><p className="mt-1 text-xs text-[#8b979e]">{index + 2} planned renewals</p><div className="mt-5 h-2 rounded-full bg-[#edf2f2]"><div className="h-2 rounded-full bg-[#4e9994]" style={{width: `${45 + index * 18}%`}}/></div></div>)}</div>}</section> }
function CameraModal({ camera, onClose }: { camera: (typeof cameras)[number]; onClose: () => void }) { return <div className="fixed inset-0 z-50 flex items-center justify-center bg-[#14222a]/40 p-4" role="dialog" aria-modal="true" aria-labelledby="camera-modal-title"><button className="absolute inset-0 cursor-default" onClick={onClose} aria-label="Close camera details"/><div className="relative max-h-[90vh] w-full max-w-[620px] overflow-y-auto rounded-2xl bg-white p-6 shadow-2xl"><div className="flex items-start justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.15em] text-[#176b71]">Camera details</p><h2 id="camera-modal-title" className="mt-1 text-xl font-extrabold">{camera.name}</h2><p className="mt-1 text-xs text-[#8b979e]">{camera.station} · {camera.location}</p></div><button onClick={onClose} className="rounded-lg p-2 text-[#8a969d] hover:bg-[#f2f5f6]" aria-label="Close"><X size={18}/></button></div><div className="mt-6 grid gap-3 sm:grid-cols-2"><Info label="Camera ID" value={camera.id}/><Info label="Network address" value={camera.address}/><Info label="Current status" value={camera.status === "online" ? "Online" : "Offline"}/><Info label="Last heartbeat" value={camera.seen}/><Info label="Firmware" value={camera.firmware}/><Info label="30-day uptime" value={camera.uptime}/></div><div className="mt-5 rounded-xl bg-[#f6f9fa] p-4"><div className="flex items-center justify-between"><p className="text-xs font-bold">Incident history</p><span className="text-[10px] text-[#8b979e]">Africa/Lagos time</span></div>{camera.incidents ? <div className="mt-3 flex items-center gap-3 text-xs"><span className="size-2 rounded-full bg-[#df5b67]"/><span className="font-semibold">Offline incident active</span><span className="ml-auto text-[#8b979e]">Started {camera.seen}</span></div> : <p className="mt-3 text-xs text-[#718087]">No unresolved incidents for this camera.</p>}</div><div className="mt-5 flex justify-end gap-2"><button className="rounded-lg border border-[#dce3e6] px-3 py-2 text-xs font-bold text-[#617079]">Acknowledge incident</button><button className="rounded-lg bg-[#176b71] px-3 py-2 text-xs font-bold text-white">View full history</button></div></div></div> }
function Info({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-[#edf0f1] p-3"><p className="text-[10px] uppercase tracking-wider text-[#9aa5ab]">{label}</p><p className="mt-1 text-sm font-bold">{value}</p></div> }
function AdminPanel() { return <div className="grid gap-5 lg:grid-cols-[1.4fr_1fr]"><section className="rounded-xl border border-[#e3e7eb] bg-white p-5"><h2 className="text-[16px] font-bold">Access approvals</h2><p className="mt-1 text-xs text-[#8b979e]">Review new accounts and assign Viewer or Admin access.</p><div className="mt-5 divide-y divide-[#edf0f1]">{[['Amina Yusuf','amina@farmalert.com','Viewer'],['David Okafor','david@farmalert.com','Admin']].map(([name,email,role]) => <div key={email} className="flex flex-col gap-3 py-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-bold">{name}</p><p className="mt-1 text-xs text-[#8b979e]">{email} · Requested today</p></div><div className="flex gap-2"><button className="rounded-lg border border-[#dce3e6] px-3 py-2 text-xs font-bold text-[#64727a]">{role}</button><button className="rounded-lg bg-[#176b71] px-3 py-2 text-xs font-bold text-white">Approve</button></div></div>)}</div></section><section className="rounded-xl border border-[#e3e7eb] bg-white p-5"><h2 className="text-[16px] font-bold">Workspace controls</h2><div className="mt-5 flex flex-col gap-3">{['Manage subscription categories','Configure alert recipients','Export full audit log','Create finance share link'].map((item) => <button key={item} className="flex items-center justify-between rounded-lg border border-[#e8edef] p-3 text-left text-xs font-semibold text-[#53626b] hover:bg-[#f7f9fa]">{item}<ChevronRight size={15}/></button>)}</div></section></div> }
function SettingsPanel() { return <div className="grid gap-5 lg:grid-cols-2"><section className="rounded-xl border border-[#e3e7eb] bg-white p-5"><h2 className="text-[16px] font-bold">Alert preferences</h2><p className="mt-1 text-xs text-[#8b979e]">Control when owners and the shared IT inbox are notified.</p><div className="mt-5 flex flex-col gap-4">{[['Renewal reminders','30, 10, 5, 1 days before expiration'],['Expiration-day alert','Send an alert when a subscription expires'],['Camera offline alerts','Notify after 10 minutes without heartbeat'],['Africa/Lagos timezone','All dates and alert times use WAT']].map(([label,detail]) => <label key={label} className="flex items-center justify-between gap-4 rounded-lg border border-[#edf0f1] p-3"><span><span className="block text-xs font-bold">{label}</span><span className="mt-1 block text-[11px] text-[#8b979e]">{detail}</span></span><input type="checkbox" defaultChecked className="size-4 accent-[#176b71]"/></label>)}</div></section><section className="rounded-xl border border-[#e3e7eb] bg-white p-5"><h2 className="text-[16px] font-bold">Integrations and backups</h2><div className="mt-5 flex flex-col gap-3">{['Resend email delivery','Slack / Teams webhook','Nightly database backup','Read-only finance link'].map((item) => <div key={item} className="flex items-center justify-between rounded-lg bg-[#f6f9fa] p-4"><span className="text-xs font-bold">{item}</span><span className="rounded-full bg-[#fff5db] px-2 py-1 text-[10px] font-bold text-[#b57920]">Not configured</span></div>)}</div><button className="mt-5 rounded-lg bg-[#176b71] px-4 py-2.5 text-xs font-bold text-white">Save settings</button></section></div> }
