'use client'

import { useEffect, useState } from 'react'
import { AppShell, PageIntro, SectionCard } from './app-shell'
import { Button } from './ui/button'

type Data = { page: any; identity: any[]; documents: any[]; blocks: any[] }
const documentTypes = '.pdf,.doc,.docx,.ppt,.pptx,.xls,.xlsx,.png,.jpg,.jpeg,.svg'
const identityLabels: Record<string, string> = { mission: 'Mission', vision: 'Vision', values: 'Core values' }

export function OnboardingManager() {
  const [data, setData] = useState<Data | null>(null)
  const [saving, setSaving] = useState(false)
  const [uploading, setUploading] = useState<string | null>(null)
  const [message, setMessage] = useState('')

  const load = async () => { const response = await fetch('/api/onboarding', { cache: 'no-store' }); const result = await response.json(); if (!response.ok) throw new Error(result.error || 'Could not load onboarding data'); setData(result) }
  useEffect(() => { load().catch((error) => setMessage(error.message)) }, [])
  if (!data) return <AppShell title="Onboarding Page Manager"><p className="text-sm text-[#718089]">{message || 'Loading onboarding settings…'}</p></AppShell>

  const update = (patch: Partial<Data>) => setData({ ...data, ...patch })
  const setPage = (key: string, value: string) => update({ page: { ...data.page, [key]: value } })
  const setIdentity = (id: string, patch: any) => update({ identity: data.identity.map((item) => item.id === id ? { ...item, ...patch } : item) })
  const setDocuments = (documents: any[]) => update({ documents: documents.map((item, index) => ({ ...item, sortOrder: index })) })
  const upload = async (file: File, previousUrl = '') => { const form = new FormData(); form.append('file', file, file.name); if (previousUrl) form.append('previousUrl', previousUrl); const response = await fetch('/api/onboarding/upload', { method: 'POST', body: form }); const result = await response.json(); if (!response.ok) throw new Error(result.error || 'Upload failed'); return result }
  const save = async () => { setSaving(true); setMessage(''); try { const response = await fetch('/api/onboarding', { method: 'PUT', headers: { 'content-type': 'application/json' }, body: JSON.stringify(data), cache: 'no-store' }); const result = await response.json(); if (!response.ok) throw new Error(result.error || 'Could not save changes'); await load(); setMessage('Saved and published successfully') } catch (error) { console.error('[v0] onboarding save failed', error); setMessage(error instanceof Error ? error.message : 'Could not save changes') } finally { setSaving(false) } }
  const uploadIdentity = async (item: any, file: File) => { setUploading(item.id); try { const result = await upload(file, item.imageUrl || ''); setIdentity(item.id, { imageUrl: result.url }); setMessage(`${identityLabels[item.itemType]} image uploaded. Save & publish to make it live.`) } catch (error) { console.error('[v0] identity upload failed', error); setMessage(error instanceof Error ? error.message : 'Image upload failed') } finally { setUploading(null) } }
  const uploadDocument = async (item: any, file: File) => { setUploading(item.id); try { const result = await upload(file, item.fileUrl || ''); setDocuments(data.documents.map((document) => document.id === item.id ? { ...document, fileUrl: result.url, fileName: result.fileName, fileType: result.fileType, fileSize: result.fileSize, title: document.title || result.fileName } : document)); setMessage('Document uploaded. Save & publish to make it live.') } catch (error) { console.error('[v0] document upload failed', error); setMessage(error instanceof Error ? error.message : 'Document upload failed') } finally { setUploading(null) } }
  const addDocument = () => setDocuments([...data.documents, { id: `new-${Date.now()}`, title: '', description: '', fileUrl: null, fileName: null, fileType: null, fileSize: null }])
  const addBlock = () => update({ blocks: [...data.blocks, { id: `new-${Date.now()}`, title: '', content: '', sortOrder: data.blocks.length }] })
  const publicUrl = `${typeof window !== 'undefined' ? window.location.origin : ''}/onboarding/${data.page.token}`

  return <AppShell title="Onboarding Page Manager"><PageIntro eyebrow="Employee experience" title="Onboarding Page Manager" description="Publish one live source of truth for new team members." action={<div className="flex gap-2"><Button secondary onClick={() => window.open(publicUrl, '_blank')}>View live page</Button><Button onClick={save}>{saving ? 'Saving…' : 'Save & publish'}</Button></div>} />{message && <p className="mb-4 rounded-xl border border-[#b8ddd0] bg-[#effaf4] px-4 py-3 text-sm font-semibold text-[#176b71]">{message}</p>}
    <div className="grid gap-5 xl:grid-cols-2">
      <SectionCard title="Welcome content" description="These fields appear directly on the public Employee onboarding page."><div className="grid gap-4"><Field label="Company name" value={data.page.companyName} onChange={(value) => setPage('companyName', value)} /><Field label="Tagline" value={data.page.tagline || ''} onChange={(value) => setPage('tagline', value)} /><Field label="Headline" value={data.page.headline || ''} onChange={(value) => setPage('headline', value)} /><label className="text-sm font-bold">Welcome message<textarea value={data.page.welcomeMessage || ''} onChange={(event) => setPage('welcomeMessage', event.target.value)} className="mt-2 min-h-32 w-full rounded-xl border border-[#dfe8e6] bg-white/80 p-3 font-normal shadow-inner" /></label></div></SectionCard>
      <SectionCard title="Who we are" description="Add the mission, vision, and values shown on the landing page."><div className="grid gap-4">{data.identity.map((item) => <div key={item.id} className="rounded-xl border border-[#dfe8e6] bg-white/70 p-4"><div className="flex items-center justify-between gap-3"><h3 className="font-extrabold text-[#183b3b]">{identityLabels[item.itemType] || item.itemType}</h3><label className="cursor-pointer rounded-lg bg-[#e9f5ee] px-3 py-2 text-xs font-bold text-[#176b71]">{uploading === item.id ? 'Uploading…' : item.imageUrl ? 'Replace image' : 'Upload image'}<input name={`${item.itemType}-image`} type="file" accept=".png,.jpg,.jpeg,.svg" className="sr-only" onChange={(event) => { const file = event.target.files?.[0]; if (file) uploadIdentity(item, file) }} /></label></div><textarea value={item.caption || ''} onChange={(event) => setIdentity(item.id, { caption: event.target.value })} placeholder={`Write your ${identityLabels[item.itemType]?.toLowerCase()}...`} className="mt-3 min-h-24 w-full rounded-xl border border-[#dfe8e6] bg-white/80 p-3 text-sm shadow-inner" />{item.imageUrl && <img src={item.imageUrl} alt={`${identityLabels[item.itemType]} preview`} className="mt-3 h-24 w-full rounded-lg object-cover" />}</div>)}</div></SectionCard>
      <SectionCard title="Information & resources" description="Upload files and publish them for new team members to download."><div className="grid gap-3">{data.documents.map((item) => <div key={item.id} className="rounded-xl border border-[#dfe8e6] bg-white/70 p-4"><div className="grid gap-3 sm:grid-cols-2"><Field label="Title" value={item.title || ''} onChange={(value) => setDocuments(data.documents.map((doc) => doc.id === item.id ? { ...doc, title: value } : doc))} /><Field label="Description" value={item.description || ''} onChange={(value) => setDocuments(data.documents.map((doc) => doc.id === item.id ? { ...doc, description: value } : doc))} /></div><div className="mt-3 flex flex-wrap items-center gap-3"><label className="cursor-pointer rounded-lg bg-[#176b71] px-3 py-2 text-xs font-bold text-white">{uploading === item.id ? 'Uploading…' : item.fileUrl ? 'Replace file' : 'Upload file'}<input name="document" type="file" accept={documentTypes} className="sr-only" onChange={(event) => { const file = event.target.files?.[0]; if (file) uploadDocument(item, file) }} /></label>{item.fileName && <span className="text-xs font-semibold text-[#65737c]">{item.fileName} · {Math.ceil((item.fileSize || 0) / 1024)} KB</span>}<button type="button" onClick={() => setDocuments(data.documents.filter((doc) => doc.id !== item.id))} className="text-xs font-bold text-red-600">Remove</button></div></div>)}<Button secondary onClick={addDocument}>Add document</Button></div></SectionCard>
      <SectionCard title="Additional information" description="Add any other onboarding writeups or policies."><div className="grid gap-3">{data.blocks.map((block) => <div key={block.id} className="rounded-xl border border-[#dfe8e6] bg-white/70 p-4"><Field label="Section title" value={block.title || ''} onChange={(value) => update({ blocks: data.blocks.map((item) => item.id === block.id ? { ...item, title: value } : item) })} /><textarea value={block.content || ''} onChange={(event) => update({ blocks: data.blocks.map((item) => item.id === block.id ? { ...item, content: event.target.value } : item) })} className="mt-3 min-h-28 w-full rounded-xl border border-[#dfe8e6] bg-white/80 p-3 text-sm shadow-inner" /></div>)}<Button secondary onClick={addBlock}>Add information section</Button></div></SectionCard>
    </div></AppShell>
}
function Field({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="text-sm font-bold">{label}<input value={value} onChange={(event) => onChange(event.target.value)} className="mt-2 h-11 w-full rounded-xl border border-[#dfe8e6] bg-white/80 px-3 font-normal shadow-inner" /></label> }
export default OnboardingManager
