'use client'

import { FormEvent, useState } from 'react'

const fields = [['requesterName', 'Your name'], ['requesterEmail', 'Your email'], ['department', 'Department'], ['approval', 'Approver name']] as const

export function PublicBrandingRequest() {
  const [submitted, setSubmitted] = useState(false)
  const [error, setError] = useState('')
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setError('')
    const form = new FormData(event.currentTarget)
    const response = await fetch('/api/branding-requests', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(Object.fromEntries(form)) })
    if (!response.ok) { setError((await response.json()).error ?? 'Unable to submit request.'); return }
    setSubmitted(true); event.currentTarget.reset()
  }
  if (submitted) return <main className="flex min-h-screen items-center justify-center bg-[#f7f9fa] p-6"><section className="w-full max-w-xl rounded-2xl border border-[#e3e8eb] bg-white p-8 shadow-sm"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#176b71]">Request received</p><h1 className="mt-2 text-3xl font-extrabold text-[#26343c]">Thanks — your request is in the queue.</h1><p className="mt-3 text-sm leading-6 text-[#718089]">The Farm Alert creative team can now review and track it from the internal dashboard.</p></section></main>
  return <main className="min-h-screen bg-[#f7f9fa] px-4 py-10 sm:px-6"><section className="mx-auto max-w-3xl rounded-2xl border border-[#e3e8eb] bg-white p-6 shadow-sm sm:p-10"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#176b71]">Farm Alert IT</p><h1 className="mt-2 text-3xl font-extrabold text-[#26343c]">New branding request</h1><p className="mt-2 text-sm leading-6 text-[#718089]">Share the brief with the creative team. No team account is required.</p><form onSubmit={submit} className="mt-8 grid gap-5 sm:grid-cols-2">{fields.map(([name, label]) => <label key={name} className="text-sm font-bold">{label}<input name={name} required type={name === 'requesterEmail' ? 'email' : 'text'} className="mt-2 h-11 w-full rounded-lg border border-[#e1e7e9] px-3 font-normal" /></label>)}<label className="text-sm font-bold">Request type<select name="requestType" className="mt-2 h-11 w-full rounded-lg border border-[#e1e7e9] px-3 font-normal"><option>Logo</option><option>Social graphic</option><option>Flyer/poster</option><option>Presentation</option><option>Signage</option><option>Email template</option><option>Other</option></select></label><label className="text-sm font-bold">Priority<select name="priority" defaultValue="Medium" className="mt-2 h-11 w-full rounded-lg border border-[#e1e7e9] px-3 font-normal"><option>Low</option><option>Medium</option><option>High</option><option>Urgent</option></select></label><label className="text-sm font-bold sm:col-span-2">Project title<input name="title" required className="mt-2 h-11 w-full rounded-lg border border-[#e1e7e9] px-3 font-normal" /></label><label className="text-sm font-bold sm:col-span-2">Deadline<input name="deadline" required type="date" className="mt-2 h-11 w-full rounded-lg border border-[#e1e7e9] px-3 font-normal" /></label><label className="text-sm font-bold sm:col-span-2">Brief<textarea name="description" required rows={4} className="mt-2 w-full rounded-lg border border-[#e1e7e9] p-3 font-normal" /></label><label className="text-sm font-bold sm:col-span-2">Target audience<input name="audience" required className="mt-2 h-11 w-full rounded-lg border border-[#e1e7e9] px-3 font-normal" /></label>{error && <p role="alert" className="sm:col-span-2 text-sm font-semibold text-[#c44857]">{error}</p>}<button className="rounded-lg bg-[#176b71] px-4 py-3 text-sm font-bold text-white sm:col-span-2">Submit request</button></form></section></main>
}
