import { eq } from 'drizzle-orm'
import { db } from '@/lib/db'
import { catalogCache, catalogSettings } from '@/lib/db/schema'
import { auth } from '@/lib/auth'
import { headers } from 'next/headers'

export const CATALOG_WEBHOOK_URL = 'https://playpen-glandular-refinery.ngrok-free.dev/webhook/catalog'
export const CATALOG_COLUMNS = ['name','item_name','item_group','stock_uom','disabled','is_stock_item','standard_rate','brand','modified','price_list','price_list_rate','currency','uom','valid_from','valid_upto'] as const
export type CatalogRow = Record<string, any>
import { parsePriceList, mappingFor, type PriceMapping } from '@/lib/catalog-utils'
export type { PriceType, PriceMapping } from '@/lib/catalog-utils'
const defaultColumns = [{ key: 'item_name', label: 'Product' }, { key: 'item_group', label: 'Category' }, { key: 'stock_uom', label: 'Unit' }]
export const defaults = { title: 'Farm Alert Product Catalog', subtitle: 'Explore our available products and current pricing.', footerText: 'Farm Alert Tech', accentColor: '#176b71', visibleColumns: defaultColumns, priceLists: [], itemGroups: [], showDisabled: false, noindex: true, mappings: [], visibleStates: [], stateOrder: [], defaultState: '', hideUnpriced: true }
export function getMappings(rows: CatalogRow[], saved: any[] = []): PriceMapping[] { const values = [...new Set(rows.map((row) => String(row.price_list ?? '').trim()).filter(Boolean))]; return values.map((value) => { const stored = saved.find((item) => item.value === value); return stored ? { ...stored } : { value, ...parsePriceList(value) } }) }
export async function getUserId() { const session = await auth.api.getSession({ headers: await headers() }); if (!session?.user) throw new Error('Unauthorized'); return session.user.id }
export async function getSettings(userId: string) { const [row] = await db.select().from(catalogSettings).where(eq(catalogSettings.userId, userId)); const stored = row?.priceLists && !Array.isArray(row.priceLists) ? row.priceLists as any : {}; return { ...defaults, ...(row ?? {}), ...stored, visibleColumns: Array.isArray(row?.visibleColumns) && row.visibleColumns.length ? row.visibleColumns : defaults.visibleColumns, mappings: Array.isArray(stored.mappings) ? stored.mappings : Array.isArray(row?.priceLists) ? row.priceLists : [], userId } }
export async function getCatalog(force = false) { const [cached] = await db.select().from(catalogCache).where(eq(catalogCache.id, 1)); const fresh = cached && !force && Date.now() - new Date(cached.fetchedAt).getTime() < 600000; if (fresh && cached.payload) return { ...JSON.parse(JSON.stringify(cached.payload)), fetchedAt: cached.fetchedAt, error: cached.errorMessage }; try { const response = await fetch(CATALOG_WEBHOOK_URL, { cache: 'no-store', headers: { Accept: 'application/json' }, signal: AbortSignal.timeout(15000) }); if (!response.ok) throw new Error(`Catalog webhook returned ${response.status}`); const raw = await response.json(); const payload = Array.isArray(raw) ? { items: raw } : raw?.items ? raw : { items: [] }; await db.insert(catalogCache).values({ id: 1, payload, fetchedAt: new Date(), errorMessage: null }).onConflictDoUpdate({ target: catalogCache.id, set: { payload, fetchedAt: new Date(), errorMessage: null } }); return { ...payload, fetchedAt: new Date(), error: null } } catch (error) { return cached ? { ...JSON.parse(JSON.stringify(cached.payload)), fetchedAt: cached.fetchedAt, error: error instanceof Error ? error.message : 'Catalog unavailable' } : { items: [], prices: [], fetchedAt: null, error: 'Catalog unavailable' } } }
export function joinCatalog(payload: { items?: CatalogRow[]; prices?: CatalogRow[] }) { const items = payload.items ?? []; if (items.some((item) => Array.isArray(item.prices))) return items.flatMap((item) => (item.prices ?? []).map((price: CatalogRow) => ({ ...item, ...price, item_code: item.item_code ?? item.name }))); return (payload.prices ?? []).map((price) => ({ ...(items.find((item) => item.name === price.item_code || item.item_code === price.item_code) ?? {}), ...price })) }
export function publicRows(rows: CatalogRow[], settings: any) { const mappings = Array.isArray(settings.mappings) ? settings.mappings : []; return rows.filter((row) => settings.showDisabled || !row.disabled).filter((row) => !settings.itemGroups?.length || settings.itemGroups.includes(row.item_group)).map((row) => { const mapping = mappingFor(row.price_list, mappings); const normalized = { ...row, price_list_rate: row.price_list_rate ?? row.rate ?? '', item_name: row.item_name ?? row.name ?? row.item_code ?? '', state: mapping.state, priceType: mapping.type }; return Object.fromEntries([...(settings.visibleColumns ?? defaultColumns).map((column: any) => [column.key, normalized[column.key] ?? '']), ['item_name', normalized.item_name, 'state', mapping.state, 'priceType', mapping.type, 'price_list_rate', normalized.price_list_rate, 'currency', normalized.currency ?? 'NGN', 'valid_from', normalized.valid_from, 'modified', normalized.modified]]) }) }
export { defaultColumns }
