import { and, eq } from 'drizzle-orm'
import { db } from '@/lib/db'
import { catalogCache, catalogSettings } from '@/lib/db/schema'
import { auth } from '@/lib/auth'
import { headers } from 'next/headers'

export const CATALOG_WEBHOOK_URL = 'https://playpen-glandular-refinery.ngrok-free.dev/webhook/catalog'
export const CATALOG_COLUMNS = ['name','item_name','item_group','stock_uom','disabled','is_stock_item','standard_rate','valuation_rate','brand','modified','price_list','price_list_rate','currency','uom','selling','buying','valid_from','valid_upto','customer','supplier'] as const
export type CatalogRow = Record<string, unknown>
const defaults = { title: 'Farm Alert Product Catalog', subtitle: 'Explore our available products and current pricing.', footerText: 'Farm Alert Tech', accentColor: '#176b71', visibleColumns: [{ key: 'item_name', label: 'Product' }, { key: 'item_group', label: 'Category' }, { key: 'stock_uom', label: 'Unit' }, { key: 'price_list', label: 'Price list' }, { key: 'price_list_rate', label: 'Price' }, { key: 'currency', label: 'Currency' }], priceLists: [], itemGroups: [], showDisabled: false, noindex: true }
export async function getUserId() { const session = await auth.api.getSession({ headers: await headers() }); if (!session?.user) throw new Error('Unauthorized'); return session.user.id }
export async function getSettings(userId: string) { const [row] = await db.select().from(catalogSettings).where(eq(catalogSettings.userId, userId)); if (!row) return { ...defaults, userId }; return { ...row, visibleColumns: Array.isArray(row.visibleColumns) && row.visibleColumns.length ? row.visibleColumns : defaults.visibleColumns, priceLists: Array.isArray(row.priceLists) ? row.priceLists : [], itemGroups: Array.isArray(row.itemGroups) ? row.itemGroups : [] } }
export async function getCatalog(force = false) { const [cached] = await db.select().from(catalogCache).where(eq(catalogCache.id, 1)); const cachedItemCount = Array.isArray((cached?.payload as any)?.items) ? (cached?.payload as any).items.length : 0; const fresh = cached && cachedItemCount > 0 && !force && Date.now() - new Date(cached.fetchedAt).getTime() < 600000; if (fresh && cached.payload) return { ...JSON.parse(JSON.stringify(cached.payload)), fetchedAt: cached.fetchedAt, error: cached.errorMessage }; try { const response = await fetch(CATALOG_WEBHOOK_URL, { cache: 'no-store', headers: { Accept: 'application/json' }, signal: AbortSignal.timeout(15000) }); if (!response.ok) throw new Error(`Catalog webhook returned ${response.status}`); const rawPayload = await response.json(); const payload = Array.isArray(rawPayload) ? { items: rawPayload } : rawPayload?.items ? rawPayload : { items: [] }; await db.insert(catalogCache).values({ id: 1, payload, fetchedAt: new Date(), errorMessage: null }).onConflictDoUpdate({ target: catalogCache.id, set: { payload, fetchedAt: new Date(), errorMessage: null } }); return { ...payload, fetchedAt: new Date(), error: null } } catch (error) { return cached ? { ...JSON.parse(JSON.stringify(cached.payload)), fetchedAt: cached.fetchedAt, error: error instanceof Error ? error.message : 'Catalog unavailable' } : { items: [], prices: [], fetchedAt: null, error: 'Catalog is temporarily unavailable.' } } }
export function joinCatalog(payload: { items?: CatalogRow[]; prices?: CatalogRow[] }) { const items = payload.items ?? []; if (items.some((item: any) => Array.isArray(item.prices))) return items.flatMap((item: any) => (item.prices ?? []).map((price: any) => ({ ...item, ...price, item_code: item.item_code ?? item.name }))); const prices = payload.prices ?? []; return prices.map((price) => ({ ...(items.find((item) => item.name === price.item_code || item.item_code === price.item_code) ?? {}), ...price })) }
export function publicRows(rows: CatalogRow[], settings: any) { return rows.filter((row) => settings.showDisabled || !row.disabled).filter((row) => !settings.priceLists?.length || settings.priceLists.includes(row.price_list)).filter((row) => !settings.itemGroups?.length || settings.itemGroups.includes(row.item_group)).map((row) => { const normalized = { ...row, price_list_rate: row.price_list_rate ?? row.rate ?? '', currency: row.currency ?? 'NGN', item_name: row.item_name ?? row.name ?? row.item_code ?? '' }; return Object.fromEntries((settings.visibleColumns ?? defaults.visibleColumns).map((column: any) => [column.key, normalized[column.key] ?? ''])) }) }
export { defaults } 
