import { randomBytes } from 'node:crypto'
import { NextRequest, NextResponse } from 'next/server'
import { eq, asc } from 'drizzle-orm'
import { headers } from 'next/headers'
import { auth } from '@/lib/auth'
import { db } from '@/lib/db'
import { onboardingPages, onboardingDocuments, onboardingIdentityItems, onboardingTextBlocks } from '@/lib/db/schema'

async function userId() { const session = await auth.api.getSession({ headers: await headers() }); if (!session?.user?.id) throw new Error('Unauthorized'); return session.user.id }
async function ensurePage(id: string) { const uid = await userId(); const [page] = await db.select().from(onboardingPages).where(eq(onboardingPages.userId, uid)); if (id && page?.id !== id) throw new Error('Not found'); return page }

export async function GET() { try { const uid = await userId(); let [page] = await db.select().from(onboardingPages).where(eq(onboardingPages.userId, uid)); if (!page) { [page] = await db.insert(onboardingPages).values({ userId: uid, token: randomBytes(32).toString('hex') }).returning(); await db.insert(onboardingIdentityItems).values(['mission','vision','values'].map((itemType, sortOrder) => ({ pageId: page.id, itemType, sortOrder }))); await db.insert(onboardingDocuments).values(['Employee Handbook','SOP – Communication','Guarantor Form','Personnel Service Agreement','Associate Information Template'].map((title, sortOrder) => ({ pageId: page.id, title, sortOrder }))); } const [identity, documents, blocks] = await Promise.all([db.select().from(onboardingIdentityItems).where(eq(onboardingIdentityItems.pageId, page.id)).orderBy(asc(onboardingIdentityItems.sortOrder)), db.select().from(onboardingDocuments).where(eq(onboardingDocuments.pageId, page.id)).orderBy(asc(onboardingDocuments.sortOrder)), db.select().from(onboardingTextBlocks).where(eq(onboardingTextBlocks.pageId, page.id)).orderBy(asc(onboardingTextBlocks.sortOrder))]); return NextResponse.json({ page, identity, documents, blocks }, { headers: { 'Cache-Control': 'no-store, max-age=0' } }) } catch { return NextResponse.json({ error: 'Unauthorized' }, { status: 401 }) } }

export async function PUT(request: NextRequest) { try { const body = await request.json(); const pageInput = body.page && typeof body.page === 'object' ? body.page : body; const current = await ensurePage(pageInput.id); if (!current) throw new Error('Onboarding page not found'); const [page] = await db.update(onboardingPages).set({ isLive: pageInput.isLive ?? true, companyName: String(pageInput.companyName ?? ''), tagline: String(pageInput.tagline ?? ''), logoUrl: pageInput.logoUrl || null, accentColor: pageInput.accentColor || '#176b71', headline: String(pageInput.headline ?? ''), welcomeMessage: String(pageInput.welcomeMessage ?? ''), additionalInfo: String(pageInput.additionalInfo ?? ''), updatedAt: new Date() }).where(eq(onboardingPages.id, current.id)).returning(); if (Array.isArray(body.identity)) for (const item of body.identity) await db.update(onboardingIdentityItems).set({ imageUrl: item.imageUrl || null, caption: String(item.caption ?? ''), updatedAt: new Date() }).where(eq(onboardingIdentityItems.id, item.id)); if (Array.isArray(body.documents)) { await db.delete(onboardingDocuments).where(eq(onboardingDocuments.pageId, current.id)); const documents = body.documents.filter((item: any) => String(item.title ?? '').trim()).map((item: any, index: number) => ({ pageId: current.id, title: String(item.title).trim(), description: String(item.description ?? ''), fileUrl: item.fileUrl || null, fileName: item.fileName || null, fileType: item.fileType || null, fileSize: Number.isFinite(item.fileSize) ? item.fileSize : null, sortOrder: index })); if (documents.length) await db.insert(onboardingDocuments).values(documents) } if (Array.isArray(body.blocks)) { await db.delete(onboardingTextBlocks).where(eq(onboardingTextBlocks.pageId, current.id)); if (body.blocks.length) await db.insert(onboardingTextBlocks).values(body.blocks.map((item: { title: string; content: string; sortOrder: number }) => ({ pageId: current.id, title: item.title, content: item.content, sortOrder: item.sortOrder }))) } return NextResponse.json(page) } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : 'Unable to save' }, { status: 400 }) } }

export async function POST(request: NextRequest) { try { const uid = await userId(); const [page] = await db.select().from(onboardingPages).where(eq(onboardingPages.userId, uid)); if (!page) return NextResponse.json({ error: 'Page not found' }, { status: 404 }); const replacement = randomBytes(32).toString('hex'); await db.update(onboardingPages).set({ token: replacement, updatedAt: new Date() }).where(eq(onboardingPages.id, page.id)); return NextResponse.json({ token: replacement }) } catch { return NextResponse.json({ error: 'Unauthorized' }, { status: 401 }) } }
